#server:
#  port: 3000
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/communi_flow?useUnicode=true&characterEncoding=utf8&useSSL=false
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  data:
#    redis:
#      password:
#      host: 127.0.0.1
#      port: 6379
#
#communi:
#  business:
#    message:
#      topic: chenzcBusinessTopic
#    log:
#      topic: chenzcLogTopic
#    graylog:
#      ip: 127.0.0.1
